In [3]:
import pickle
import pandas as pd

tickers = ['PCAR', 'LUV', 'JCI', 'GE', 'GD', 'DE', 'DAL', 'CMI', 'CAT', 'ABB']
temp_dir = {'SYMBOL' : [],
            'INDUSTRIES' : [],
            'RETURN' : [],
            'SCORE' : []}


for ticker in tickers:
    with open(f'score/{ticker}.pkl', 'rb') as f:
        rank = pickle.load(f)
        temp_dir['SYMBOL'].append(rank[0])
        temp_dir['INDUSTRIES'].append(rank[1])
        temp_dir['RETURN'].append(rank[3])
        temp_dir['SCORE'].append(rank[2])

ranking = pd.DataFrame(temp_dir)
ranking = ranking.sort_values('SCORE', ascending=False)
ranking['RANK'] = [i for i in range(1, len(ranking) + 1)]
ranking.set_index('RANK', inplace=True)
ranking

     SYMBOL   INDUSTRIES     RETURN     SCORE
RANK
1       CAT  Industrials  58.036679  4.501568
2       JCI  Industrials  54.738964  3.732348
3       LUV  Industrials   7.602173  3.361906
4       DAL  Industrials  -3.145393  1.844476
5      PCAR  Industrials  23.427597  1.381577
6        GE  Industrials -24.534252  0.702446
7       ABB  Industrials  -7.079720 -1.502597
8       CMI  Industrials   7.240774 -1.858724
9        DE  Industrials  15.617183 -3.843382
10       GD  Industrials -41.477319 -6.191232