In [2]:
import pickle
import pandas as pd

tickers = ['WPP', 'VZ', 'TU', 'RELX', 'OMC', 'NFLX', 'GOOG', 'EA', 'DISCA', 'DIS']
temp_dir = {'SYMBOL' : [],
            'INDUSTRIES' : [],
            'RETURN' : [],
            'SCORE' : []}


for ticker in tickers:
    with open(f'score/{ticker}.pkl', 'rb') as f:
        rank = pickle.load(f)
        temp_dir['SYMBOL'].append(rank[0])
        temp_dir['INDUSTRIES'].append(rank[1])
        temp_dir['RETURN'].append(rank[3])
        temp_dir['SCORE'].append(rank[2])

ranking = pd.DataFrame(temp_dir)
ranking = ranking.sort_values('SCORE', ascending=False)
ranking['RANK'] = [i for i in range(1, len(ranking) + 1)]
ranking.set_index('RANK', inplace=True)
ranking

     SYMBOL              INDUSTRIES      RETURN     SCORE
RANK
1      NFLX  Communication Services  213.250655  4.223527
2       OMC  Communication Services   12.731507  2.790298
3       DIS  Communication Services   30.862771  1.720816
4        VZ  Communication Services   13.447865  1.590646
5     DISCA  Communication Services   30.985060  0.831245
6        EA  Communication Services   25.607737  0.646616
7      GOOG  Communication Services   63.744535  0.498554
8      RELX  Communication Services    0.446860 -0.777418
9        TU  Communication Services  -11.695908 -3.071598
10      WPP  Communication Services  -60.886850 -3.934010