In [3]:
import pickle
import pandas as pd

tickers = ['XOM', 'TOT', 'SNP', 'RDS-B', 'PTR', 'EQNR', 'CVX', 'COP', "BP", 'ENB']
temp_dir = {'SYMBOL' : [],
            'INDUSTRIES' : [],
            'RETURN' : [],
            'SCORE' : []}


for ticker in tickers:
    with open(f'score/{ticker}.pkl', 'rb') as f:
        rank = pickle.load(f)
        temp_dir['SYMBOL'].append(rank[0])
        temp_dir['INDUSTRIES'].append(rank[1])
        temp_dir['RETURN'].append(rank[3])
        temp_dir['SCORE'].append(rank[2])

ranking = pd.DataFrame(temp_dir)
ranking = ranking.sort_values('SCORE', ascending=False)
ranking['RANK'] = [i for i in range(1, len(ranking) + 1)]
ranking.set_index('RANK', inplace=True)
ranking

     SYMBOL INDUSTRIES     RETURN     SCORE
RANK
1       COP     Energy  22.326266  4.534028
2       TOT     Energy   9.760835  3.523890
3       PTR     Energy -28.438243  2.959738
4      EQNR     Energy   0.369148  2.348318
5       XOM     Energy -33.845739  2.332854
6       CVX     Energy -10.510882  2.199123
7       SNP     Energy -22.616000  1.764657
8       ENB     Energy  -8.691048  1.182704
9     RDS-B     Energy -43.332752  0.004924
10       BP     Energy -49.433055 -1.534616