In [3]:
import pickle
import pandas as pd

tickers = ['WY', 'WPC', 'VTR', 'SPG', 'O', 'NLY', 'MPW', 'HST', 'AVB', "ARE"]
temp_dir = {'SYMBOL' : [],
            'INDUSTRIES' : [],
            'RETURN' : [],
            'SCORE' : []}


for ticker in tickers:
    with open(f'score/{ticker}.pkl', 'rb') as f:
        rank = pickle.load(f)
        temp_dir['SYMBOL'].append(rank[0])
        temp_dir['INDUSTRIES'].append(rank[1])
        temp_dir['RETURN'].append(rank[3])
        temp_dir['SCORE'].append(rank[2])

ranking = pd.DataFrame(temp_dir)
ranking = ranking.sort_values('SCORE', ascending=False)
ranking['RANK'] = [i for i in range(1, len(ranking) + 1)]
ranking.set_index('RANK', inplace=True)
ranking

     SYMBOL   INDUSTRIES      RETURN      SCORE
RANK
1        WY  Real Estate  109.786804  10.869924
2       WPC  Real Estate   24.879605   5.401321
3       MPW  Real Estate   82.177293   4.192969
4       VTR  Real Estate    7.273857   1.774714
5       SPG  Real Estate  -27.300407   1.712667
6       NLY  Real Estate  -22.685888   0.439659
7       HST  Real Estate  -28.361187  -0.502237
8       ARE  Real Estate   18.680015  -1.485158
9         O  Real Estate   -6.963294  -1.650534
10      AVB  Real Estate  -28.158955  -3.237105